server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: certification-monitor
  
  # 数据库配置 - 使用Zeabur环境变量
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    
    # Druid连接池配置 - 针对Zeabur云环境优化
    druid:
      initial-size: 1          # 减少初始连接数
      min-idle: 1              # 减少最小空闲连接
      max-active: 5            # 减少最大连接数
      max-wait: 30000          # 减少等待时间
      time-between-eviction-runs-millis: 30000  # 更频繁检查
      min-evictable-idle-time-millis: 180000    # 减少空闲时间
      validation-query: SELECT 1
      validation-query-timeout: 5
      test-while-idle: true
      test-on-borrow: true     # 云环境建议开启
      test-on-return: false
      remove-abandoned: true
      remove-abandoned-timeout: 180
      log-abandoned: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      # 连接超时优化
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000;connectTimeout=10000;socketTimeout=30000

  # Redis配置 - 暂时禁用
  # data:
  #   redis:
  #     host: ${SPRING_DATA_REDIS_HOST:localhost}
  #     port: ${SPRING_DATA_REDIS_PORT:6379}
  #     database: 0
  #     timeout: 2000ms
  #     lettuce:
  #       pool:
  #         max-active: 8
  #         max-idle: 8
  #         min-idle: 0
  #         max-wait: -1ms

  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  # JPA配置 - 改为validate模式防止数据丢失
  jpa:
    hibernate:
      ddl-auto: validate  # 从update改为validate，防止意外删除表或数据
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        show_sql: false
    open-in-view: false

# 日志配置 - 针对云环境优化
logging:
  level:
    com.certification: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    com.alibaba.druid: INFO
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  # 在云环境中，日志通常输出到stdout
  file:
    name: /app/logs/certification-monitor.log
    path: /app/logs/

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: false
    redis:
      enabled: false
    db:
      enabled: true

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
    enable-version: false
    enable-reload-cache-parameter: false
    enable-after-script: true
    enable-filter-multipart-api-method-type: POST
    enable-filter-multipart-apis: false
    enable-request-cache: true
    enable-host: false
    enable-host-text: ""
    enable-home-custom: false
    home-custom-path: ""
    enable-search: true
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: Copyright © 2024 认证监控系统
    enable-dynamic-parameter: false
    enable-debug: false
    enable-open-api: false
    enable-group: true

# 火山引擎翻译服务配置
volcengine:
  translate:
    access-key: ${VOLCENGINE_ACCESS_KEY:}
    secret-key: ${VOLCENGINE_SECRET_KEY:}
    region: cn-north-1
    api-url: https://translate.volcengineapi.com

# 应用自定义配置
app:
  cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
    allowed-headers: "*"
    max-age: 3600
  
  scraper:
    user-agent: "CertificationMonitor/1.0"
    timeout: 30000
    retry-count: 3
  
  cache:
    ttl: 3600
    max-size: 1000

# 风险计算配置
risk:
  calculation:
    decay-factor: 0.5
    max-score: 20.0
    relevance-threshold: 0.7
    enable-detailed-logging: false
    ttl: 3600
    max-size: 1000
  
  risk:
    high-threshold: 0.7
    medium-threshold: 0.4
    low-threshold: 0.2
  
  notification:
    slack:
      enabled: false
      webhook-url: ""
    email:
      enabled: false
      smtp-host: ""
      smtp-port: 587
      username: ""
      password: ""
      from: ""
      to: []
  
  visualization:
    chart:
      width: 800
      height: 600
      theme: default
